name: OpenRouter
provider_type: openrouter
enabled: true
connection:
  base_url: "https://openrouter.ai/api/v1"
  api_key_env: OPENROUTER_API_KEY
default_model: anthropic/claude-haiku-4.5
defaults:
  temperature: 0.5
extra_headers:
  HTTP-Referer: https://valuecell.ai
  X-Title: ValueCell
models:
- id: anthropic/claude-haiku-4.5
  name: Claude Haiku 4.5
- id: x-ai/grok-4
  name: Grok 4
- id: qwen/qwen-max
  name: Qwen Max
- id: openai/gpt-5
  name: GPT-5
- id: google/gemini-2.5-flash
  name: Gemini 2.5 Flash
- id: google/gemini-2.5-pro
  name: Gemini 2.5 Pro
- id: openai/gpt-5-mini
  name: GPT-5 Mini
- id: qwen/qwen3-max
  name: Qwen3 Max
- id: anthropic/claude-sonnet-4.5
  name: Claude Sonnet 4.5
